// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABRpb5aSnTBRP2x0M2AfvhM9PDkOmCUZg',
    appId: '1:626320569600:web:c277113af3ce540711afe5',
    messagingSenderId: '626320569600',
    projectId: 'ai-historical-debate-app',
    authDomain: 'ai-historical-debate-app.firebaseapp.com',
    storageBucket: 'ai-historical-debate-app.firebasestorage.app',
    measurementId: 'G-BMBX5R55Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8tQt5uZ8zQeahyvDRTG2cTPVVi7zSTqA',
    appId: '1:626320569600:android:7d53894f3e25490511afe5',
    messagingSenderId: '626320569600',
    projectId: 'ai-historical-debate-app',
    storageBucket: 'ai-historical-debate-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjZ5mhumhNZtIRXDUwElnUI6zOX88UVlg',
    appId: '1:626320569600:ios:b2f26e8e348bac8711afe5',
    messagingSenderId: '626320569600',
    projectId: 'ai-historical-debate-app',
    storageBucket: 'ai-historical-debate-app.firebasestorage.app',
    iosBundleId: 'com.example.historyDebate',
  );
}
